// Runs before the plugin entry's static imports evaluate: self-heal the
// generated module aliases when they are missing.
//
// WHY: `node_modules/openclaw` (the directory alias that re-exports
// `src/plugin-sdk/`) and the `node_modules/@openclaw/*` stub packages do not
// exist in source control -- they are generated by
// `plugin/scripts/link-openclaw-alias.mjs`, which already runs as postinstall
// on every install. This bootstrap is only the belt-and-suspenders guard: if
// the generated tree went away afterwards (an npm cache cleanup, a manual
// wipe of `node_modules`), regenerate it now, before the first
// `openclaw/plugin-sdk/*` import below fails to resolve.
//
// It is best effort on purpose: a read-only install (the npm cache dir)
// cannot be written to, in which case the spawn fails silently and the import
// error surfaces with the real cause instead of a mysterious spawn crash.
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const aliasManifest = path.join(here, "node_modules", "openclaw", "package.json");
if (!existsSync(aliasManifest)) {
  const linkScript = path.join(here, "plugin", "scripts", "link-openclaw-alias.mjs");
  if (existsSync(linkScript)) {
    try {
      spawnSync(process.execPath, [linkScript], { stdio: "ignore" });
    } catch {
      // Nothing to do: report the missing alias through the import failure
      // rather than masking it with a bootstrap error.
    }
  }
}
